admin/Room_Management/urls.py
# urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('room_list/', room_list, name='room_list'),
    path('add/', add_room, name='add_room'),
    path('edit/<int:room_id>/', edit_room, name='edit_room'),
    path('delete/<int:room_id>/', delete_room, name='delete_room'),
    path('search/', search_rooms, name='search_rooms'),




    path('facilities/',facility_list, name='facility_list'),
     path('facilities/add/', add_facility, name='add_facility'),
    path('facilities/edit/<int:facility_id>/', edit_facility, name='edit_facility'),
    path('facilities/delete/<int:facility_id>/',delete_facility, name='delete_facility'),
]

admin/admin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Admin_Management.urls')),
    path('chat/', include('chat.urls')),
     path('room/', include('Room_Management.urls')),
     path('communication/', include('Chat_System.urls')),
    path('ticket/', include('Ticket_Management.urls')),
    path('emails/',include('emails.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin/chat/urls.py
# chat/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", index, name="index"),
    path("<str:room_name>/", room, name="room"),
    path('start_chat/<str:username>', start_chat, name="start_chat"),
    path('room/<uuid:room_id>/delete/', delete_chat, name='delete_chat'),  # Change `int:room_id` to `uuid:room_id`
    path('second_user_profile/<uuid:room_id>/', second_user_profile_view, name='second_user_profile_view'),

]

admin/Room_Management/models.py
from django.db import models
from django.contrib.auth.models import User

class Room(models.Model):
    room_number = models.CharField(max_length=50)
    available_seat = models.IntegerField()
    TYPE_CHOICES = [
        ('single', 'Single'),
        ('double', 'Double'),
        ('triple', 'Triple'),
        ('customized', 'Customized'),
    ]
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    available_date = models.DateField(null=True,blank=True)
    floor = models.IntegerField()

    def __str__(self):
        return self.room_number

# models.py
from django.db import models

class Facility(models.Model):
    FACILITY_TYPES = [
        ('gym', 'Gym'),
        ('pool', 'Swimming Pool'),
        ('wifi', 'WiFi'),
        ('laundry', 'Laundry'),
        ('parking', 'Parking'),
        ('other', 'Other'),
    ]

    facility_type = models.CharField(max_length=20, choices=FACILITY_TYPES,blank=True, null=True)
    facility_name = models.CharField(max_length=100,blank=True, null=True)
    facility_image = models.ImageField(upload_to='facility_images/', blank=True, null=True)

    def __str__(self):
        return self.facility_name

admin/Room_Management/forms.py
# forms.py
from django import forms
from .models import Room

class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['room_number', 'available_seat', 'type', 'available_date', 'floor']




# forms.py
from django import forms
from .models import Facility

class FacilityForm(forms.ModelForm):
    class Meta:
        model = Facility
        fields = ['facility_type', 'facility_name', 'facility_image']

admin/Room_Management/views.py
# views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Room
from .forms import RoomForm

def add_room(request):
    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('room_list')
    else:
        form = RoomForm()
    return render(request, 'add_room.html', {'form': form})

def edit_room(request, room_id):
    room = get_object_or_404(Room, pk=room_id)
    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('room_list')
    else:
        form = RoomForm(instance=room)
    return render(request, 'edit_room.html', {'form': form})

def delete_room(request, room_id):
    room = get_object_or_404(Room, pk=room_id)
    if request.method == 'POST':
        room.delete()
        return redirect('room_list')
    return render(request, 'delete_room.html', {'room': room})

def room_list(request):
    rooms = Room.objects.all()
    return render(request, 'room_list.html', {'rooms': rooms})


from django.shortcuts import render
from .models import Room


from .models import Room
from django.shortcuts import render, redirect

def search_rooms(request):
    if request.method == 'GET':
        start_date = request.GET.get('start_date')
        room_type = request.GET.get('room_type')

        # Perform room availability check based on start date and room type
        available_rooms = Room.objects.filter(type=room_type, available_seat__gt=0)

        context = {
            'start_date': start_date,
            'room_type': room_type,
            'available_rooms': available_rooms,
        }
        return render(request, 'search_room.html', context)

























# views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Facility
from .forms import FacilityForm

def facility_list(request):
    facilities = Facility.objects.all()
    sort_by = request.GET.get('sort_by')
    if sort_by in ['facility_type', 'facility_name']:
        facilities = facilities.order_by(sort_by)
    elif sort_by == 'facility_id':
        facilities = facilities.order_by('id')
    
    return render(request, 'facility_list.html', {'facilities': facilities})
# views.py
from django.shortcuts import render, redirect
from .models import Facility
from .forms import FacilityForm

def add_facility(request):
    if request.method == 'POST':
        form = FacilityForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('facility_list')
    else:
        form = FacilityForm()
    return render(request, 'add_facility.html', {'form': form})


def edit_facility(request, facility_id):
    facility = get_object_or_404(Facility, id=facility_id)
    if request.method == 'POST':
        form = FacilityForm(request.POST, request.FILES, instance=facility)
        if form.is_valid():
            form.save()
            return redirect('facility_list')
    else:
        form = FacilityForm(instance=facility)
    return render(request, 'edit_facility.html', {'form': form})

def delete_facility(request, facility_id):
    facility = get_object_or_404(Facility, id=facility_id)
    facility.delete()
    return redirect('facility_list')

admin/Room_Management/templates/add_facility.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Facilities{% endblock %}
{% block extra_css %}
    <style>
        .add_fac {
            text-align: center;
            margin-top: 20px;
            font-size: 28px;
            color: #333;
            font-weight: bold;
        }
        .fac_form {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 8px;
        }
        .fac_form label {
            font-size: 16px;
            color: #555;
        }
        .fac_form input[type="text"],
        .fac_form input[type="file"],
        .fac_form select,
        .fac_form textarea {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }
        .fac_form button {
            width: 100%;
            padding: 12px 20px;
            background-color: #1775F1;
            color: #fff;
            font-size: 18px;
            font-weight: bold;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .fac_form button:hover {
            background-color: #125bb5;
        }
        .back-link {
            display: block;
            text-align: center;
            margin-top: 20px;
            font-size: 16px;
            color: #1775F1;
            text-decoration: none;
            font-weight: bold;
        }
        .back-link:hover {
            text-decoration: underline;
            color: #125bb5;
        }
    </style>
{% endblock %}

{% block content %}
    <h2 class="add_fac">Add New Facility</h2>
    <form class="fac_form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Facility</button>
    </form>
    <a href="{% url 'facility_list' %}" class="back-link">Back to Facilities List</a>
{% endblock %}

admin/Room_Management/templates/add_room.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Room{% endblock %}

{% block content %}
    <section class="services py-5">
        <div class="container d-flex justify-content-center">
            <div class="card card-custom shadow-sm">
                <div class="card-body">
                    <h2 class="text-center mt-5 mb-4">Add <span class="text-primary">Room</span></h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-primary btn-custom">Add Room</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <style>
        .card-custom {
            border: 1px solid #ddd;
            width: 400px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
           
            margin: auto;
        }

        .card-body {
            padding: 20px;
        }

        .btn-custom {
            background-color: var(--blue); /* Replace with your color variable if defined */
            color: white;
            padding: 10px 20px;
            font-size: 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease, transform 0.3s ease, box-shadow 0.3s ease, border 0.3s ease;
            text-decoration: none;
            position: relative; /* Required for slide effect */
            overflow: hidden; /* Hide the sliding effect overflow */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* Initial shadow */
        }

        .btn-custom:hover {
            color: var(--blue); /* Change text color on hover */
            transform: translateY(-10px); /* Move button up more on hover */
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3); /* Deeper shadow on hover */
            border: 1px solid #D75192; /* Pink border on hover */
        }

        
        .text-primary {
            color: var(--blue); /* Primary color */
        }
    </style>
{% endblock %}

admin/Room_Management/templates/delete_room.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Delete_Room{% endblock title %}
{% block content %}
    <h1>Delete Room</h1>
    <p>Are you sure you want to delete room "{{ room.room_number }}"?</p>
    <form action="{% url 'delete_room' room.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
{% endblock content %}

admin/Room_Management/templates/edit_facility.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Edit Facilities{% endblock %}

{% block extra_css %}
    <style>
        .edit_fac {
            text-align: center;
            margin-top: 20px;
            font-size: 28px;
            color: #333;
            font-weight: bold;
        }
        .edit_form {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 8px;
        }
        .edit_form label {
            font-size: 16px;
            color: #555;
        }
        .edit_form input[type="text"],
        .edit_form input[type="file"],
        .edit_form select,
        .edit_form textarea {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }
        .edit_form button {
            width: 100%;
            padding: 12px 20px;
            background-color: #1775F1;
            color: #fff;
            font-size: 18px;
            font-weight: bold;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .edit_form button:hover {
            background-color: #125bb5;
        }
        .edit_form a {
            display: block;
            text-align: center;
            margin-top: 20px;
            font-size: 16px;
            color: #1775F1;
            text-decoration: none;
            font-weight: bold;
        }
        .edit_form a:hover {
            text-decoration: underline;
            color: #125bb5;
        }
    </style>
{% endblock %}

{% block content %}
    <h2 class="edit_fac">Edit Facility</h2>
    <form class="edit_form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
    <a href="{% url 'facility_list' %}">Back to List</a>
 {% endblock %}

admin/Room_Management/templates/edit_room.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Edit_Room{% endblock title %}
{% block content %}
    <h2 class="text-center mt-5 mb-3">Update</u><span class="text-primary">Rooms Details</span></h2>

    <section class="services py-5 ">
        <div class="container mx-auto"> <!-- Centering the container -->
            <div class="row justify-content-center"> <!-- Centering the row -->
                <div class="col-sm-12 col-md-4 col-lg-4 col-12">
                    <div class="card mb-5">

                        <div class="card-body text-center"> <!-- Centering the card content -->
                            <form method="post" class="my-auto"> <!-- Adding custom class for vertical centering -->
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary">Update Room</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

admin/Room_Management/templates/facility_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Facilities List{% endblock %}

{% block extra_css %}
    
    <style>
        .facility-list {
            margin: 20px;
            text-align: center;
        }
        table {
            width: 100%;
            background-color: #fff;
            border-collapse: collapse;
        }
        th, td {
            border-bottom: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            font-weight: 600;
            font-size: 20px;
            background-color: #fff;
        }
        .action-icons {
            display: flex;
            gap: 10px;
        }
        .action-icons a {
            text-decoration: none;
            color: black;
        }
        .add-facility-btn {
            display: inline-block;
            margin: 20px 0;
            padding: 10px 20px;
            background-color: #1775F1;
            color: #fff;
            font-size: 18px;
            font-weight: bold;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }
        .add-facility-btn:hover {
            background-color: #125bb5;
        }
    </style>
{% endblock %}

{% block content %}
    <h2 class="facility-list">Facilities Details List</h2>
    <a href="{% url 'add_facility' %}" class="add-facility-btn">Add New Facility</a>
    <table>
        <thead>
            <tr>
                <th>Facility ID</th>
                <th>Facility Type</th>
                <th>Facility Name</th>
                <th>Facility Image</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for facility in facilities %}
            <tr>
                <td>{{ facility.id }}</td>
                <td>{{ facility.get_facility_type_display }}</td>
                <td>{{ facility.facility_name }}</td>
                <td>
                    {% if facility.facility_image %}
                        <img src="{{ facility.facility_image.url }}" alt="{{ facility.facility_name }}" width="100">
                    {% else %}
                        No Image
                    {% endif %}
                </td>
                <td class="action-icons">
                    <a href="{% url 'edit_facility' facility.id %}"><i style="color: #1775F1; font-size:24px;" class='bx bxs-edit'></i></a>
                    <a href="{% url 'delete_facility' facility.id %}" onclick="return confirm('Are you sure you want to delete this facility?');"><i style="color:#FC3B56; font-size:24px;" class='bx bxs-trash'></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

admin/Room_Management/templates/room_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Room List{% endblock %}

{% block content %}

<style>
    .btn-custom {
        background-color: var(--blue); /* Ensure you have defined this variable or replace it with a color value */
        color: white;
        padding: 10px 20px;
        font-size: 16px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s ease, transform 0.3s ease, box-shadow 0.3s ease, border 0.3s ease;
        text-decoration: none;
        display: inline-block;
        position: relative; /* Required for slide effect */
        overflow: hidden; /* Hide the sliding effect overflow */
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* Initial shadow */
    }
    
    .btn-custom span {
        position: relative;
        z-index: 1; /* Ensures text is above the white sliding effect */
    }

    .mt-custom {
        margin-top: 50px; /* Adjust this value as needed */
    }

    .room-table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
        margin-bottom: 20px;
        background-color: #ffffff;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .room-table th, .room-table td {
        padding: 15px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    .room-table th {
        background-color: var(--blue); /* Ensure you have defined this variable or replace it with a color value */
        color: white;
        font-weight: bold;
    }

    .room-table tr:hover {
        background-color: #f1f1f1;
    }

    .btn-update {
        background-color: var(--blue); /* Define this variable or use a color value */
        color: white;
        padding: 8px 16px;
        border-radius: 4px;
        border: none;
        cursor: pointer;
    }

    .btn-delete {
        background-color: red;
        color: white;
        padding: 8px 16px;
        border-radius: 4px;
        border: none;
        cursor: pointer;
    }

    .text-center {
        text-align: center;
    }

    .no-rooms-found {
        margin-top: 20px;
        color: #666;
        font-size: 18px;
        text-align: center;
    }
</style>

<div class="add">
    {% if user.is_superuser %}
    <div class="text-center">
        <a href="{% url 'add_room' %}" class="btn-custom mt-custom"><span class='addroom'>Add Room</span></a>
    </div>
    {% endif %}
</div>

<section class="services py-5 bg-light">
    <div class="container">
        <table class="room-table">
            <thead>
                <tr>
                    <th>Room Number</th>
                    <th>Available Seats</th>
                    <th>Type</th>
                    <th>Available Date</th>
                    <th>Floor</th>
                    {% if user.is_superuser %}
                    <th>Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for room in rooms %}
                <tr>
                    <td>{{ room.room_number }}</td>
                    <td>{{ room.available_seat }}</td>
                    <td>{{ room.get_type_display }}</td>
                    <td>{{ room.available_date }}</td>
                    <td>{{ room.floor }}</td>
                    {% if user.is_superuser %}
                    <td>
                        
                        <a href="{% url 'edit_room' room.id %}" class="btn-update">Update</a>
                        <form action="{% url 'delete_room' room.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn-delete">Delete</button>
                        </form>
                    </td>
                    {% endif %}
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6" class="no-rooms-found">No rooms found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-JZsoBh1E0lb3HuYe6yK/BZjE/Z9TbdzN+lKQQpQppgyN7tyydm9i0h5Mcdm2XrZJ" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-p5wFtoqGC7Fk4xkY3e5AUV0P7yymTUK4TkfFVag8G/hV8tC3I5gKYE2vL1OoM3DJ" crossorigin="anonymous"></script>
{% endblock %}

admin/Room_Management/templates/search_room.html
{% block title %}Search_Room{% endblock %}
{% load static %}
{% block style %}
 
{% endblock %}
{% block content %}
   
    <h1 class="text-center">Available Rooms</h1>
    <p>Start Date: {{ start_date }}</p>
    <p>Room Type: {{ room_type }}</p>

    <div class="container">
        <div class="row">
            {% for room in available_rooms %}
            <div class="col-sm-12 col-md-4 col-lg-4 col-12 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Room Number: {{ room.room_number }}</h5>
                        <p class="card-text">Available Seats: {{ room.available_seat }}</p>
                        <p class="card-text">Type: {{ room.get_type_display }}</p>
                        <p class="card-text">Available Date: {{ room.available_date }}</p>
                        <p class="card-text">Floor: {{ room.floor }}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col">
                <div class="alert alert-warning" role="alert">
                    No rooms available for the selected criteria.
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}